### PR TITLE
Added Troubleshooting.md

### PR DESCRIPTION
**Pull request by akram-rameez**
In reference to #26, I've added a getter function to the header lib, which could be used by the developer, by `console.log({headers: headers.get()})`

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-nodejs?pullRequest=34) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-nodejs?pullRequest=34) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-nodejs?pullRequest=34) it.</sub>

**Comment by akram-rameez** [comment]
This could also be added on to `sendgrid-nodejs` mail class.

**Comment by akram-rameez** [comment]
I hadn't seen noticed `jsonString()` functionality and initially taken reference from the python sdk. Nonetheless, I have modified it so that the new doc (and comments) both have adequate information.

**Comment by akram-rameez** [comment]
Hey guys, any idea why is build failing? It passes for the more recent version and rejects legacy versions.

**Comment by mbernier** [comment]
@akram-rameez You may have to merge master again - I believe that we removed the older versions from travis.yml, which should solve the build issue.

**Comment by thinkingserious** [comment]
Hello @akram-rameez,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@akram-rameez 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
