### PR TITLE
fix issue where concat was used incorrectly

### PR DESCRIPTION
**Pull request by limianwang**

### CODE REVIEW

**Comment by limianwang** [comment]
It would be great if we can merge this and publish. Thanks!

**Comment by limianwang** [comment]
@eddiezane Wondering if you (or anyone else with admin) can do a quick code-review and merge? Thanks!

**Comment by eddiezane** [comment]
Thanks for the ping, @limianwang!

Apologies but I don't work for SendGrid any more.

@thinkingserious or @mbernier might be able to help out though.

**Comment by limianwang** [comment]
Thanks! 

@thinkingserious @mbernier Can one of you review this? I'm kind of depending on this module.

**Comment by thinkingserious** [comment]
Hello @limianwang,

Thanks for the pull request and apologies for the delay!

Please submit a signed CLA so we can get this merged: https://github.com/sendgrid/smtpapi-nodejs/blob/master/CONTRIBUTING.md#cla

Thank you for your support!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @limianwang,

Just checking in :)

**Comment by limianwang** [comment]
@thinkingserious ah sorry for the delay, somehow didn't see this notifications. Is that supposed to be email version?

**Comment by thinkingserious** [comment]
@limianwang,

Yes, please email the signed CLA to dx@sendgrid.com. Thanks!

**Comment by limianwang** [comment]
@thinkingserious Done.

**Comment by thinkingserious** [comment]
Hello @limianwang,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
